### ISSUE TITLE
Pull down fix for Burning Bug

### ISSUE THREAD

**Issue by devopsralf** [a3rk/remix#1]
ETN has it. 

https://github.com/electroneum/electroneum/commit/ba7df94886e7943bdeefb0389ed379045e51ce7c

@routed3 you mentioned you wanted to take a stab at this. Let me know if not and I will jump on it.

**Comment by routed3** [comment]
@devopsralf  If you can get to it, go for it

[monero commit](https://github.com/monero-project/monero/commit/e350cc5ad557eba67790551f96bbbcfc97173480)
[ryo commit](https://github.com/ryo-currency/ryo-currency/pull/124/commits/5985a6916e426cd52446b2a58691c976e80a9da1)
