### ISSUE TITLE
Remix web wallet UI issue

### ISSUE THREAD

**Issue by ghost** [a3rk/remix#21]
There is overlapping in remix web wallet text. Please check attached picture.
Web wallet does not sync more than 99.9% it seems like getting stuck.

![image](https://user-images.githubusercontent.com/36481616/49672060-3061e700-fa6a-11e8-9850-a4a7ee802b27.png)

**Comment by drparadoxical** [comment]
@vikaspatel111087 - the web wallet is a separate repository, please submit potential issues there. I'll leave this open for a bit so you've some time before closing it out accordingly.

**Comment by ghost** [comment]
@drparadoxical  I am closing this issue now. I have created a new issue under remix-web-wallet repository. Thanks for the feedback.

**Comment by drparadoxical** [comment]
Thank you @vikaspatel111087
